# cargo-mutants configuration.

additional_cargo_args = ["--all-features"]

# serde's `Visitor::expecting` mutations are not very interesting.
exclude_re = [
    "for (DocumentVisitor|KeyVisitor|ValidatedVisitor)>::expecting ",
]
