[package]
name = "oxide-versioned-envelope"
version = "0.1.0"
description = "Versioned JSON envelopes."
readme = "README.md"
documentation = "https://docs.rs/oxide-versioned-envelope"
repository = "https://github.com/oxidecomputer/oxide-versioned-envelope"
keywords = ["json", "serde", "versioning", "envelope", "compatibility"]
categories = ["encoding", "data-structures"]
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg=doc_cfg"]

[lints]
workspace = true

[dependencies]
schemars08 = { workspace = true, optional = true }
serde_core.workspace = true
serde_json.workspace = true

[dev-dependencies]
serde.workspace = true
thiserror.workspace = true

[features]
default = []
schemars08 = ["dep:schemars08"]

[package.metadata.cargo-sync-rdme.badge.badges]
license = true
crates-io = true
docs-rs = true
rust-version = true

[package.metadata.release]
pre-release-replacements = [
    { file = "../../CHANGELOG.md", search = "Unreleased", replace = "[{{version}}]", min = 1 },
    { file = "../../CHANGELOG.md", search = "ReleaseDate", replace = "{{date}}", min = 1 },
    { file = "../../CHANGELOG.md", search = "<!-- next-header -->", replace = "<!-- next-header -->\n## Unreleased - ReleaseDate\n", exactly = 1 },
    { file = "../../CHANGELOG.md", search = "<!-- next-url -->", replace = "<!-- next-url -->\n[{{version}}]: https://github.com/oxidecomputer/oxide-versioned-envelope/releases/tag/oxide-versioned-envelope-{{version}}", exactly = 1 },
]
